version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: sqldb
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Admin
      POSTGRES_DB: postgres
    ports:
      - "5435:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    container_name: sql
    restart: always
    ports:
      - "8000:8000"
    environment:
      - GROQ_API_KEY=${GROQ_API_KEY}
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env

  frontend:
    build: ./frontend
    container_name: db
    restart: always
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  pgdata: